# Generated by Django 3.1.2 on 2020-10-22 17:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('circle', '0002_auto_20201020_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post_images/'),
        ),
        migrations.AlterField(
            model_name='circle',
            name='members',
            field=models.ManyToManyField(related_name='circles', through='circle.CircleMembership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='circlemembership',
            name='circle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='circle.circle'),
        ),
    ]
